data:
  folder_path: delta-lake_data/datalake

cassandra:
  key_space: spark_streams
  table_name: created_users

source: 
  kafka_topics: users_created
  kafka.bootstrap.servers: localhost:9092
  kafka_options:     
    startingOffsets: earliest
    endingOffsets: latest